#
# This source file is part of the CoughSync based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

project: CoughSync.xcodeproj
schemes:
- CoughSync
